name: CI

on: push

jobs:
  unit_tests:
    name: checking
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    container:
      image: docker://srzzumix/googletest:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: cmake . && make
      - name: tests
        run: ./unit-tests
