name: CI

on: push

jobs:
  unit_tests:
    name: checking
    runs-on: ubuntu-latest
    container:
      image: docker://srzzumix/googletest:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
